######################################################################
# Automatically generated by qmake (2.01a) ? 7? 12 10:39:50 2013
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += Slide.cpp
