######################################################################
# Automatically generated by qmake (2.01a) ? 7? 7 10:29:47 2013
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += FullScreen.h
SOURCES += FullScreen.cpp
